name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@1c4632ccc198d4c9b34d9e6b3d556c6f245b4e69 # main
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@1c4632ccc198d4c9b34d9e6b3d556c6f245b4e69 # main
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 18
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
