name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@bcb53d910698d29749511f386139ad8180269101 # main
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@bcb53d910698d29749511f386139ad8180269101 # main
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 18
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}
